//PACKAGE COM.PATEL.REDIS;
//
//IMPORT ORG.JUNIT.JUPITER.API.TEST;
//IMPORT ORG.SPRINGFRAMEWORK.BOOT.TEST.CONTEXT.SPRINGBOOTTEST;
//
//@SPRINGBOOTTEST
//CLASS REDISAPPLICATIONTESTS {
//
//	@TEST
//	VOID CONTEXTLOADS() {
//	}
//
//}
